### ISSUE TITLE
trimBody handling of listed descriptions

### ISSUE THREAD

**Issue by natevenn** [LookingForMe/lookingForFrontEnd#26]
If a description is listed on the site with bullet points it show the bullet points and doesnt truncate appropriately.

**Comment by ksk5280** [comment]
I was checking out making ajax calls to different pages and there are a few pages that do not render and have an error like the following: 
`Uncaught Invariant Violation: Danger: Expected markup to render 25 nodes, but rendered 18.`

I think this is also due to the trimbody method if it cuts a tag in half, i.e. splitting `<br />` because of the space in the tag.
