### ISSUE TITLE
"View Detail" Button

### ISSUE THREAD

**Issue by Salvi6God** [LookingForMe/lookingForFrontEnd#63]
If anyone opens up a new tab when clicking on “view detail” it gives back an error but if you click on the button directly the page renders the job post.

![Buggy Bug](https://media.giphy.com/media/l0HlHGb2PS1W7QfsI/giphy.gif)

**Comment by Salvi6God** [comment]
I also want to point out that the URL is exactly the same and does not change for the two types of ways to "click" on the "view details" button.

**Comment by s-espinosa** [comment]
Leaving breadcrumbs here to help as we come back to this:

* Odd that I can replicate this in production, and when running npm start, but not when running npm run dev. Not sure if that holds some clue as to what is happening.
* Believe this might have something to do with React-Router. Don't explicitly have a route in our server.js file for jobs/:id, but a <Link /> component is being invoked and handling this click.
* Setting target="_blank" in the link tag causes all clicks to render in a new tab, so it does seem that it's possible to pass all required info and render in a new tab.

**Comment by s-espinosa** [comment]
Think I found some additional information. Originally had thought there might be a chance that this was related to the component itself, but appears to be due to the way we've set up react router.

Additional information [here](http://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually), and [here](https://github.com/newtriks/generator-react-webpack/issues/141).
